#############################################################################
# Makefile for building: IHM4Moteurs
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  IHM4Moteurs.pro
# Template: app
# Command: /home/okori/Programmes/linux/qt/5.7/gcc_64/bin/qmake -spec linux-g++ -o Makefile IHM4Moteurs.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Programmes/linux/qt/5.7/gcc_64/include -I../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets -I../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui -I../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork -I../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore -I. -I. -I../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/okori/Programmes/linux/qt/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = IHM4Moteurs1.0.0
DISTDIR = /home/okori/Developpement/Qt/IHM4Moteurs/.tmp/IHM4Moteurs1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/okori/Programmes/linux/qt/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -lVLCQtCore -lVLCQtWidgets -L/home/okori/Programmes/linux/qt/5.7/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		tcpclient.cpp qrc_assets.cpp \
		moc_mainwindow.cpp \
		moc_tcpclient.cpp
OBJECTS       = main.o \
		mainwindow.o \
		tcpclient.o \
		qrc_assets.o \
		moc_mainwindow.o \
		moc_tcpclient.o
DIST          = ihm4moteur.qmodel \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/toolchain.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/qt.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/resources.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/moc.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/uic.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/lex.prf \
		IHM4Moteurs.pro mainwindow.h \
		tcpclient.h main.cpp \
		mainwindow.cpp \
		tcpclient.cpp
QMAKE_TARGET  = IHM4Moteurs
DESTDIR       = 
TARGET        = IHM4Moteurs


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: IHM4Moteurs.pro ../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/toolchain.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/qt.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/resources.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/moc.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/uic.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/lex.prf \
		IHM4Moteurs.pro \
		assets.qrc \
		../../../Programmes/linux/qt/5.7/gcc_64/lib/libQt5Widgets.prl \
		../../../Programmes/linux/qt/5.7/gcc_64/lib/libQt5Gui.prl \
		../../../Programmes/linux/qt/5.7/gcc_64/lib/libQt5Network.prl \
		../../../Programmes/linux/qt/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ -o Makefile IHM4Moteurs.pro
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/spec_pre.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/unix.conf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/linux.conf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/sanitize.conf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/gcc-base.conf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/g++-base.conf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/common/g++-unix.conf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/qconfig.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/qt_functions.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/qt_config.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/toolchain.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/default_pre.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/resolve_config.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/default_post.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/warn_on.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/qt.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/resources.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/moc.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/uic.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/unix/thread.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/file_copies.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/exceptions.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/yacc.prf:
../../../Programmes/linux/qt/5.7/gcc_64/mkspecs/features/lex.prf:
IHM4Moteurs.pro:
assets.qrc:
../../../Programmes/linux/qt/5.7/gcc_64/lib/libQt5Widgets.prl:
../../../Programmes/linux/qt/5.7/gcc_64/lib/libQt5Gui.prl:
../../../Programmes/linux/qt/5.7/gcc_64/lib/libQt5Network.prl:
../../../Programmes/linux/qt/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile IHM4Moteurs.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents assets.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h tcpclient.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp tcpclient.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_assets.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_assets.cpp
qrc_assets.cpp: assets.qrc \
		../../../Programmes/linux/qt/5.7/gcc_64/bin/rcc \
		ressource/uncheck.png \
		ressource/check.png \
		ressource/camera.png
	/home/okori/Programmes/linux/qt/5.7/gcc_64/bin/rcc -name assets assets.qrc -o qrc_assets.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_tcpclient.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_tcpclient.cpp
moc_mainwindow.cpp: ../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QMainWindow \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfont.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QFile \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		tcpclient.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QTcpSocket \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkRequest \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QSharedDataPointer \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QString \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QUrl \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QVariant \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkReply \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QIODevice \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QSslConfiguration \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslerror.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcryptographichash.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qssl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QFlags \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QtGlobal \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QMetaType \
		mainwindow.h \
		../../../Programmes/linux/qt/5.7/gcc_64/bin/moc
	/home/okori/Programmes/linux/qt/5.7/gcc_64/bin/moc $(DEFINES) -I/home/okori/Programmes/linux/qt/5.7/gcc_64/mkspecs/linux-g++ -I/home/okori/Developpement/Qt/IHM4Moteurs -I/home/okori/Programmes/linux/qt/5.7/gcc_64/include -I/home/okori/Programmes/linux/qt/5.7/gcc_64/include/QtWidgets -I/home/okori/Programmes/linux/qt/5.7/gcc_64/include/QtGui -I/home/okori/Programmes/linux/qt/5.7/gcc_64/include/QtNetwork -I/home/okori/Programmes/linux/qt/5.7/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_tcpclient.cpp: ../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QTcpSocket \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkRequest \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QSharedDataPointer \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QString \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QUrl \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QVariant \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkReply \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QIODevice \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QSslConfiguration \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslerror.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcryptographichash.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qssl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QFlags \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QtGlobal \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QMetaType \
		tcpclient.h \
		../../../Programmes/linux/qt/5.7/gcc_64/bin/moc
	/home/okori/Programmes/linux/qt/5.7/gcc_64/bin/moc $(DEFINES) -I/home/okori/Programmes/linux/qt/5.7/gcc_64/mkspecs/linux-g++ -I/home/okori/Developpement/Qt/IHM4Moteurs -I/home/okori/Programmes/linux/qt/5.7/gcc_64/include -I/home/okori/Programmes/linux/qt/5.7/gcc_64/include/QtWidgets -I/home/okori/Programmes/linux/qt/5.7/gcc_64/include/QtGui -I/home/okori/Programmes/linux/qt/5.7/gcc_64/include/QtNetwork -I/home/okori/Programmes/linux/qt/5.7/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tcpclient.h -o moc_tcpclient.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../Programmes/linux/qt/5.7/gcc_64/bin/uic
	/home/okori/Programmes/linux/qt/5.7/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QMainWindow \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfont.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QFile \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		tcpclient.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QTcpSocket \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkRequest \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QSharedDataPointer \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QString \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QUrl \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QVariant \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkReply \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QIODevice \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QSslConfiguration \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslerror.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcryptographichash.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qssl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QFlags \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QtGlobal \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QMetaType \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QApplication \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qapplication.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qeventloop.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qguiapplication.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QMainWindow \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfont.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QFile \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		tcpclient.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QTcpSocket \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkRequest \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QSharedDataPointer \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QString \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QUrl \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QVariant \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkReply \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QIODevice \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QSslConfiguration \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslerror.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcryptographichash.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qssl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QFlags \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QtGlobal \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QMetaType \
		ui_mainwindow.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QAction \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qaction.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qactiongroup.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QApplication \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qapplication.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qeventloop.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qguiapplication.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qinputmethod.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QButtonGroup \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qbuttongroup.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QCheckBox \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qcheckbox.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QFrame \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qframe.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QHeaderView \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qheaderview.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qstyleoption.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qvalidator.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qregularexpression.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qslider.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qabstractslider.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qstyle.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qtabbar.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qrubberband.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QLabel \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qlabel.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QLineEdit \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qlineedit.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qtextcursor.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qtextformat.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpen.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qtextoption.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QMenuBar \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qmenubar.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qmenu.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QPushButton \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qpushbutton.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QSlider \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

tcpclient.o: tcpclient.cpp tcpclient.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QTcpSocket \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkRequest \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QSharedDataPointer \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QString \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QUrl \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QVariant \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkReply \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QIODevice \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QSslConfiguration \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslsocket.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslerror.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qcryptographichash.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qssl.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QFlags \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QtGlobal \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QMetaType \
		mainwindow.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/QMainWindow \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfont.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QFile \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Programmes/linux/qt/5.7/gcc_64/include/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpclient.o tcpclient.cpp

qrc_assets.o: qrc_assets.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_assets.o qrc_assets.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_tcpclient.o: moc_tcpclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpclient.o moc_tcpclient.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

